### ISSUE TITLE
Search field suggestion

### ISSUE THREAD

**Issue by jmfernandez** [VeraPancaldiLab/GARDEN-NET#64]
A way to improve the search field is suggesting through a label or information text what can be written. You have an example [here](https://react-bootstrap.github.io/components/forms/)

**Comment by mimame** [comment]
I think is fixed with https://github.com/VeraPancaldiLab/GARDEN-NET/commit/35808009657f41b34fa0e6202d78ddb295cb7006

Don't hesitate to reopen it if the bug still exits
